### ISSUE TITLE
Agent GPU Temperature Value Error while trying developer build 

### ISSUE THREAD

**Issue by tiaden** [kasmtech/workspaces-issues#229]
Hello,
While trying the developer build on the same server, the agent could not display any agent information. Therefore I could not start any workspaces. After a little investigation, I found that it was due to the fact that my vgpu temperature always return N/A in our cloud infrastructure. I thought this is something that might need fixing. 

Build info: {"commit_sha" : "191163e16b8ac3cce5aff7b5f92a588fc8def46c", "build_sha256" : "6621746f7709e01860f452e88aa2a6d48aa76ad0bfaaff83970c494a0d83f462", "date":"2022-07-01T18:45:30+0000" 

Host: nividia-smi command
![host-nvidia-smi](https://user-images.githubusercontent.com/33968665/177470594-acfa51ea-f246-45e7-9256-4281205c1d7b.png)

KasmWeb manager logs
![kasm-manager-logs](https://user-images.githubusercontent.com/33968665/177470605-4dc8761f-370d-4f26-ac86-cffaccfb83ba.png)
}

**Comment by mmcclaskey** [comment]
Would you be able to provide your cloud provider and instance type specifications?

**Comment by tiaden** [comment]
@mmcclaskey,
I'm on a private openstack cloud and using ubuntu 20.04 with kernel version 5.4.
Please let me know if you further questions

**Comment by mmcclaskey** [comment]
We just merged in a fix. If nvidia-smi reports an invalid number for any of the stats, we replace with a 0. Since I can't replicate your issue, I can only state that it should now not throw an exception, but instead show all 0s for the temp stat.

You may need to re-install workspaces using the latest dev release. You can attempt the following instead of re-installing, since the only change is in the agent container.

```
sudo docker rm -f kasm_agent
sudo docker pull kasmweb/agent:develop
sudo /opt/kasm/bin/start
```

**Comment by tiaden** [comment]
Thank you @mmcclaskey. I installed the new version and it's working as you said. I'm still not able to use the graphics acceleration. I will open another issue about it. By the way the new version looks great !

**Comment by mmcclaskey** [comment]
We just released 1.11.0, please see the latest docs for 1.11.0 the GPU how to had lots of changes.

https://kasmweb.com/docs/latest/how_to/gpu.html

**Comment by tiaden** [comment]
Excellent ! I can't wait to upgrade our current installation. thank you for letting me know :)

**Comment by tiaden** [comment]
@mmcclaskey, I tried using the gpu but I got this error
![Screen Shot 2022-07-08 at 10 57 33 AM](https://user-images.githubusercontent.com/33968665/178017943-545c636b-b644-4853-848b-3dbe516082d5.png)
I believe my gpu card is at /dev/dri/card1 instead of /dev/dri/card0
![Screen Shot 2022-07-08 at 11 00 43 AM](https://user-images.githubusercontent.com/33968665/178018556-cf13b83c-f9be-483f-bd51-28382c69c1f7.png)
![Screen Shot 2022-07-08 at 11 11 33 AM](https://user-images.githubusercontent.com/33968665/178020481-3b870c56-4811-44ed-be92-df7c90893816.png)
 I tried setting the environment variable KASM_EGL_CARD in the run configuration to /dev/dri/card1 but it did not work. Any pointers on this issue ?

**Comment by mmcclaskey** [comment]
Yes, I see that we have a bug, given the limited hardware we have available to test with. I will provide an update when we have a fix on the develop release.

**Comment by tiaden** [comment]
Great, I can't wait to test it out. Please let me know as soon as possible :)

**Comment by xLorak** [comment]
Yeah, NVIDIA GPU is broken still, i see in agent PCI address, model, and vendor only and with this order of P400 Quadro card, but i can't pass it to workspaces, because agent isn't  recognizing anyway GPU properly.

**Comment by j-travis** [comment]
@xLorak ,
Are you sure you are experiencing the same issue

 Log into the Workspaces UI as an admin, Select Agents, then select view next to the Agent listed. Is the GPU listed under Disk Info? Can you expand the GPU info section and send a screenshot.
 
 Can you ssh into the Kasm server and run the following commands and provide the poutput?
 
 ```
sudo docker info | grep Runtime
sudo lshw -c display
sudo ls -la /dev/dri
nvidia-smi
```

Can you confirm you are running the 1.11.0 release build?

**Comment by tiaden** [comment]
Please, do you have any news on this?

**Comment by j-travis** [comment]
@tiaden ,
This week we've been able to get a hardware setup in the lab to reproduce the problem. We should be able to get a fix up in the developer preview builds within a week or so. 
We will be sure to update this ticket when its available

**Comment by tiaden** [comment]
Great, Thank you very much for the update !

**Comment by j-travis** [comment]
@tiaden , sorry for the delay.

This issue should be corrected now in the latest developer preview build. Can you give it a try and confirm?

You can find out more about the developer preview builds here:
https://kasmweb.com/docs/latest/developers/builds.html

**Comment by tiaden** [comment]
@j-travis 
I confirm ! it is working now !!. The right card is selected and I was able to launch workspaces with GPU access.
![Screen Shot 2022-08-27 at 11 39 54 PM](https://user-images.githubusercontent.com/33968665/187056312-7fcba956-4bec-4da8-b8c1-6d25e7b0fef3.png)
 
Thank you very much !
